"""Generate both reader contracts from the versioned JSON; --check never writes."""
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[2]
source = root / "nmm-protect/apkprotect/src/main/resources/reader-formats.json"
data = json.loads(source.read_text(encoding="utf-8"))
java = ["// Generated by scripts/generate-reader-formats.py; edit reader-formats.json.",
        "package com.nmmedit.apkprotect.dex2c;", "", "public final class ReaderFormats {",
        "    private ReaderFormats() {}"]
cpp = ["// Generated by scripts/generate-reader-formats.py; edit reader-formats.json.",
       "#ifndef NMMP_READER_FORMATS_H", "#define NMMP_READER_FORMATS_H"]
for name, value in data["domains"].items():
    java.append(f"    public static final int {name} = {value};")
    cpp.append(f"#define NMMP_READER_{name} {value}u")
java.extend(["    public static int[] recipe(String format) {", "        switch (format) {"])
for name, (width, branch) in data["formats"].items():
    java.append(f'            case "{name}": return new int[]{{{width}, {branch}}};')
java.extend(["            default: throw new IllegalArgumentException(\"Unsupported reader format: \" + format);",
             "        }", "    }", "    public static boolean wide(String opcode) {", "        switch (opcode) {"])
for name in data["wideOpcodes"]:
    java.append(f'            case "{name}":')
java.extend(["                return true;", "            default: return false;", "        }", "    }", "}"])
java.pop()  # final class brace
java.extend(["    public static boolean unsupported(String opcode) {", "        switch (opcode) {"])
for name in data["unsupportedOpcodes"]:
    java.append(f'            case "{name}":')
java.extend(["                return true;", "            default: return false;", "        }", "    }", "}"])
cpp.append("#endif")
outputs = {
    root / "nmm-protect/apkprotect/src/main/java/com/nmmedit/apkprotect/dex2c/ReaderFormats.java": java,
    root / "nmmvm/nmmvm/src/main/cpp/vm/include/VmReaderFormats.h": cpp,
}
for path, lines in outputs.items():
    content = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"Stale reader contract: {path}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8"))
