"""Generate Java/C native VM contracts; --check only verifies existing files."""
import argparse
import json
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
root = Path(__file__).resolve().parents[2]
data = json.loads((root / "nmm-protect/apkprotect/src/main/resources/native-program-format.json").read_text(encoding="utf-8"))
assert len(data["ops"]) == data["constants"]["OP_COUNT"]
assert len({op["name"] for op in data["ops"]}) == len(data["ops"])
notice = "// Generated by scripts/generate-native-format.py; edit native-program-format.json."
java = [notice, "package com.nmmedit.apkprotect.dex2c;", "", "public final class NativeFormats {",
        "    private NativeFormats() {}"]
c = [notice, "#ifndef NMMP_NATIVE_FORMATS_H", "#define NMMP_NATIVE_FORMATS_H", "#include <stdint.h>"]

def constant(name, value):
    java.append(f"    public static final int {name} = {value};")
    c.append(f"#define NMMP_NATIVE_{name} {value}u")

for name, value in data["constants"].items():
    constant(name, value)
for name, value in data["fields"].items():
    constant("OFFSET_" + name, value)
for name, value in data["usedFieldBits"].items():
    constant("USES_" + name, value)
for index, op in enumerate(data["ops"]):
    constant(op["name"], index)
constant("VALUE_REGISTER", data["return"]["valueRegister"])
constant("STATUS_REGISTER", data["return"]["statusRegister"])
constant("SUCCESS_STATUS", data["return"]["successStatus"])
constant("FAILURE_VALUE", data["return"]["failureValue"])
java.extend(["    public static int usedFields(int opcode) {", "        switch (opcode) {"])
for op in data["ops"]:
    mask = sum(data["usedFieldBits"][name] for name in op["fields"])
    java.append(f"            case {op['name']}: return {mask};")
    c.append(f"#define NMMP_NATIVE_FIELDS_{op['name']} {mask}u")
java.extend(["            default: return -1;", "        }", "    }", "}"])
c.append("#endif")
outputs = {
    root / "nmm-protect/apkprotect/src/main/java/com/nmmedit/apkprotect/dex2c/NativeFormats.java": java,
    root / "nmmvm/nmmvm/src/main/cpp/vm/include/NativeFormats.h": c,
}
for path, lines in outputs.items():
    content = "\n".join(lines) + "\n"
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"Stale native VM contract: {path}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8"))
