// Generated by scripts/generate-native-format.py; edit native-program-format.json.
package com.nmmedit.apkprotect.dex2c;

public final class NativeFormats {
    private NativeFormats() {}
    public static final int INSTRUCTION_BYTES = 16;
    public static final int MAX_INSTRUCTIONS = 256;
    public static final int MAX_STEPS = 1024;
    public static final int REGISTERS = 16;
    public static final int DOMAIN = 1314278705;
    public static final int OP_COUNT = 14;
    public static final int OFFSET_OP = 0;
    public static final int OFFSET_DST = 1;
    public static final int OFFSET_A = 2;
    public static final int OFFSET_B = 3;
    public static final int OFFSET_IMM = 4;
    public static final int OFFSET_TARGET = 12;
    public static final int OFFSET_RESERVED = 14;
    public static final int USES_DST = 1;
    public static final int USES_A = 2;
    public static final int USES_B = 4;
    public static final int USES_IMM = 8;
    public static final int USES_TARGET = 16;
    public static final int LOAD_INPUT = 0;
    public static final int CONST = 1;
    public static final int MOV = 2;
    public static final int XOR = 3;
    public static final int AND = 4;
    public static final int OR = 5;
    public static final int ADD = 6;
    public static final int SUB = 7;
    public static final int MUL = 8;
    public static final int SHL = 9;
    public static final int SHR = 10;
    public static final int JULT = 11;
    public static final int JMP = 12;
    public static final int RETURN = 13;
    public static final int VALUE_REGISTER = 0;
    public static final int STATUS_REGISTER = 1;
    public static final int SUCCESS_STATUS = 1;
    public static final int FAILURE_VALUE = 0;
    public static int usedFields(int opcode) {
        switch (opcode) {
            case LOAD_INPUT: return 3;
            case CONST: return 9;
            case MOV: return 3;
            case XOR: return 7;
            case AND: return 7;
            case OR: return 7;
            case ADD: return 7;
            case SUB: return 7;
            case MUL: return 7;
            case SHL: return 7;
            case SHR: return 7;
            case JULT: return 22;
            case JMP: return 16;
            case RETURN: return 0;
            default: return -1;
        }
    }
}
