// Generated by scripts/generate-reader-formats.py; edit reader-formats.json.
package com.nmmedit.apkprotect.dex2c;

public final class ReaderFormats {
    private ReaderFormats() {}
    public static final int FETCH = 1;
    public static final int OPERAND = 2;
    public static final int WIDE = 3;
    public static final int PAYLOAD = 4;
    public static final int TRIES = 5;
    public static final int RECORD = 6;
    public static final int MAP = 7;
    public static final int DIRECTORY = 8;
    public static int[] recipe(String format) {
        switch (format) {
            case "Format10t": return new int[]{1, 0};
            case "Format10x": return new int[]{1, 0};
            case "Format11n": return new int[]{1, 0};
            case "Format11x": return new int[]{1, 0};
            case "Format12x": return new int[]{1, 0};
            case "Format20t": return new int[]{2, 1};
            case "Format21c": return new int[]{2, 0};
            case "Format21ih": return new int[]{2, 0};
            case "Format21lh": return new int[]{2, 0};
            case "Format21s": return new int[]{2, 0};
            case "Format21t": return new int[]{2, 1};
            case "Format22b": return new int[]{2, 0};
            case "Format22c": return new int[]{2, 0};
            case "Format22s": return new int[]{2, 0};
            case "Format22t": return new int[]{2, 1};
            case "Format22x": return new int[]{2, 0};
            case "Format23x": return new int[]{2, 0};
            case "Format30t": return new int[]{3, 1};
            case "Format31c": return new int[]{3, 0};
            case "Format31i": return new int[]{3, 0};
            case "Format31t": return new int[]{3, 2};
            case "Format32x": return new int[]{3, 0};
            case "Format35c": return new int[]{3, 0};
            case "Format3rc": return new int[]{3, 0};
            case "Format51l": return new int[]{5, 0};
            case "PackedSwitchPayload": return new int[]{0, 3};
            case "SparseSwitchPayload": return new int[]{0, 4};
            case "ArrayPayload": return new int[]{0, 5};
            default: throw new IllegalArgumentException("Unsupported reader format: " + format);
        }
    }
    public static boolean wide(String opcode) {
        switch (opcode) {
            case "CONST_WIDE_16":
            case "CONST_WIDE_32":
            case "CONST_WIDE":
            case "CONST_WIDE_HIGH16":
                return true;
            default: return false;
        }
    }
    public static boolean unsupported(String opcode) {
        switch (opcode) {
            case "INVOKE_POLYMORPHIC":
            case "INVOKE_POLYMORPHIC_RANGE":
            case "INVOKE_CUSTOM":
            case "INVOKE_CUSTOM_RANGE":
            case "CONST_METHOD_HANDLE":
            case "CONST_METHOD_TYPE":
                return true;
            default: return false;
        }
    }
}
