#ifndef NMMP_PROTECTION_POLICY_TYPES_H
#define NMMP_PROTECTION_POLICY_TYPES_H

#include <stdint.h>

typedef enum {
    NMMP_PROTECTION_CLEAN = 0,
    NMMP_PROTECTION_SUSPICIOUS = 1,
    NMMP_PROTECTION_UNKNOWN = 2,
    NMMP_PROTECTION_INTEGRITY_FAILURE = 3
} NmmpProtectionState;

#define NMMP_REASON_DEBUG UINT32_C(1)
#define NMMP_REASON_INJECTION UINT32_C(2)
#define NMMP_REASON_INTEGRITY UINT32_C(4)

#define NMMP_POLICY_ENFORCE UINT32_C(1)
#define NMMP_POLICY_CHECK_DEBUG UINT32_C(2)
#define NMMP_POLICY_CHECK_MAPS UINT32_C(4)

#endif
