#ifndef NMMP_PROTECTION_POLICY_TYPES_H
#define NMMP_PROTECTION_POLICY_TYPES_H

#include <stdint.h>

typedef enum {
    NMMP_PROTECTION_CLEAN = 0,
    NMMP_PROTECTION_SUSPICIOUS = 1,
    NMMP_PROTECTION_UNKNOWN = 2,
    NMMP_PROTECTION_INTEGRITY_FAILURE = 3
} NmmpProtectionState;

#define NMMP_REASON_DEBUG UINT32_C(1)
#define NMMP_REASON_INJECTION UINT32_C(2)
#define NMMP_REASON_INTEGRITY UINT32_C(4)
#define NMMP_REASON_NATIVE_UNAVAILABLE UINT32_C(8)
#define NMMP_REASON_ENVIRONMENT UINT32_C(16)
#define NMMP_REASON_CLOCK_UNAVAILABLE UINT32_C(32)
#define NMMP_REASON_ART_UNAVAILABLE UINT32_C(64)
#define NMMP_REASON_ART_ENTRY UINT32_C(128)
#define NMMP_REASON_ART_RUNTIME_MODIFIED UINT32_C(256)
#define NMMP_REASON_ART_RUNTIME_UNAVAILABLE UINT32_C(512)
#define NMMP_REASON_CALLER_STACK UINT32_C(1024)
#define NMMP_REASON_ALL (NMMP_REASON_DEBUG | NMMP_REASON_INJECTION | NMMP_REASON_INTEGRITY \
                         | NMMP_REASON_NATIVE_UNAVAILABLE | NMMP_REASON_ENVIRONMENT \
                         | NMMP_REASON_CLOCK_UNAVAILABLE | NMMP_REASON_ART_UNAVAILABLE \
                         | NMMP_REASON_ART_ENTRY | NMMP_REASON_ART_RUNTIME_MODIFIED \
                         | NMMP_REASON_ART_RUNTIME_UNAVAILABLE | NMMP_REASON_CALLER_STACK)

#define NMMP_POLICY_ENFORCE UINT32_C(1)
#define NMMP_POLICY_CHECK_DEBUG UINT32_C(2)
#define NMMP_POLICY_CHECK_MAPS UINT32_C(4)
#define NMMP_POLICY_CHECK_ENVIRONMENT UINT32_C(8)

#endif
