// Generated by scripts/generate-reader-formats.py; edit reader-formats.json.
#ifndef NMMP_READER_FORMATS_H
#define NMMP_READER_FORMATS_H
#define NMMP_READER_FETCH 1u
#define NMMP_READER_OPERAND 2u
#define NMMP_READER_WIDE 3u
#define NMMP_READER_PAYLOAD 4u
#define NMMP_READER_TRIES 5u
#define NMMP_READER_RECORD 6u
#define NMMP_READER_MAP 7u
#define NMMP_READER_DIRECTORY 8u
#endif
